FizzBuzzApp/FizzBuzz/Models/FizzBuzz.cs
namespace FizzBuzz.Models
{
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    public class FizzBuzz
    {
        [Display(Name = "Enter a number")]
        [Required(ErrorMessage = "Enter a valid number")]
        [Range(1, 1000, ErrorMessage = "Enter the number between 1 and 1000")]
        public int InputNumber { get; set; }

        public IPagedList<string> DisplayList { get; set; }
        public int PageNumber { get; set; }
    }
}

FizzBuzzApp/FizzBuzz/Controllers/FizzBuzzController.cs
namespace FizzBuzz.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using FizzBuzz.Business.Interfaces;
    using FizzBuzz.Models;
    using PagedList;

    public class FizzBuzzController : Controller
    {
        private const int PAGESIZE = 20;
        private readonly IFizzBuzzBusiness fizzBuzzBusiness;

        public FizzBuzzController(IFizzBuzzBusiness fizzBuzzBusiness)
        {
            this.fizzBuzzBusiness = fizzBuzzBusiness;
        }

        // GET: Fizbuzz
        [HttpGet]
        public ActionResult Fizzbuzz()
        {
            return this.View("Fizzbuzz");
        }

        [HttpPost]
        public ActionResult Fizzbuzz(FizzBuzz model)
        {
            if (this.ModelState.IsValid)
            {
                model.PageNumber = 1;
                model.DisplayList = this.GetFizzBuzzList(model.InputNumber).ToPagedList(1, PAGESIZE);
            }

            return this.View("Fizzbuzz", model);
        }

        public ActionResult GetPages(int inputNumber, int pageNumber, int linkValue)
        {
            FizzBuzz model = new FizzBuzz
            {
                InputNumber = inputNumber,
            };
            model.PageNumber = pageNumber + linkValue;
            model.DisplayList = this.GetFizzBuzzList(model.InputNumber).ToPagedList(model.PageNumber, PAGESIZE);
            return this.View("Fizzbuzz", model);
        }

        private IEnumerable<string> GetFizzBuzzList(int inputNumber)
        {
            return this.fizzBuzzBusiness.GetFizzBuzzList(inputNumber);
        }
    }
}

FizzBuzzApp/FizzBuzz/Views/FizzBuzz/FizzBuzz.cshtml
@using FizzBuzz.HtmlHelpers
@model FizzBuzz.Models.FizzBuzz
@{
    ViewBag.Title = "Fizbuzz";
}


<br />
@using (Html.BeginForm("Fizzbuzz", "FizzBuzz", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

    <div id="col-md-1"></div>
    <div id="col-md-4">

    </div>
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InputNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.InputNumber, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            <div class="col-md-3">
                @Html.ValidationMessageFor(model => model.InputNumber, "", new { @class = "text-danger" })
                <p style="color:red" id="validationMessage"></p>
            </div>

        </div>
        <div class="form-group" id="button-margin">
            <input type="submit" value="Create" class="btn btn-default" id="button-validate" />
        </div>

    </div>
}
@if (Model != null && Model.DisplayList != null)
{
    <div class="container">

        <div class="container">
            <div class="col-md-4">
                <ul>
                    @foreach (var item in Model.DisplayList)
                    {
                        <li>
                            @Html.FizzBuzzValueBuilder(item)
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="container">
            <div class="col-md-1">
                @if (Model.DisplayList.HasPreviousPage)
                {
                    @Html.ActionLink("Prev", "GetPages", new { inputNumber = Model.InputNumber, pageNumber = Model.PageNumber, linkValue = -1 }, new { @class = "button-custom" })
                }
            </div>
            <div class="col-md-offset-0 col-md-1">
                @if (Model.DisplayList.HasNextPage)
                {
                    @Html.ActionLink("Next", "GetPages", new { inputNumber = Model.InputNumber, pageNumber = Model.PageNumber, linkValue = +1 }, new { @class = "button-custom" })
                }
            </div>


        </div>
    </div>
}

FizzBuzzApp/FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/Style.css" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <h3 style="color:white">Fizbuzz</h3>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>